// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewtpvozwvukmokdudfej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3dHB2b3p3dnVrbW9rZHVkZmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwNzY3OTUsImV4cCI6MjA1NjY1Mjc5NX0.fR-wQ6Qd1XAZtwWa16mg2RSDDcg9xQYvs5bkjY-pbHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);